name: Publish to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Flake8 Jupyter Notebook
        uses: mhitza/flake8-jupyter-notebook@v1.0.5
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bencdr/code-server-deploy-container:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
